### ISSUE TITLE
BELLA-4: ECS Auto Scaling Case Study

### ISSUE THREAD

**Issue by bellanov** [bellanov/alexei-aws#11]
Implement a **Case Study** in which _Amazon ECS_ is utilized in a _Fargate_ configuration.

**Tasks:**
- [X] Develop a _NodeJS_ **service** to deploy in a _Docker_ container
- [ ] **CICD** the service via _CodeBuild_ / _CodeDeploy_
- [ ] Store Container **artifact** in _CodeArtifact_
- [ ] Deploy the container as an ECS **Fargate** _task_
- [ ] Add **auto scaling** (1-5) and a correlating **load balancer** to the ECS _Task_
- [ ] _Load test_ the **auto scaling** of the service via _Apache jMeter_

**Comment by bellanov** [comment]
No need for this PoC. Just mess around here whenever possible.

**cloudbuild.yaml** == **buildspec.yaml** essentially
